##########################################
### VSCode Extension - REST Client 필요 ###
##########################################
### 통신 테스트 할 서버
@server = http://localhost:3000

### GET 요청 보내기
GET {{server}}/boards/

### POST
POST {{server}}/boards
Content-Type: application/json

{    
    "title": "내 이름은 익.",
    "description": "열심히 나아가보자" 
}

### id 조회
GET {{server}}/boards/111

### 삭제
DELETE  {{server}}/boards/2e56c460-3996-11ee-b752-e9378b977782

### 수정
PATCH {{server}}/boards/e05734f0-39a6-11ee-aaeb-e56d4f569c2f/status
Content-Type: application/json

{
    "status": "private"
}