##########################################
### VSCode Extension - REST Client 필요 ###
##########################################
### 통신 테스트 할 서버
@server = http://localhost:3000

### GET 요청 보내기
GET {{server}}/boards/

### POST
POST {{server}}/boards
Content-Type: application/json

{    
    "title": "내 이름은 익.",
    "description": "열심히 나아가보자" 
}

### id 조회
GET {{server}}/boards/2

### 삭제
DELETE  {{server}}/boards/1

### 수정
PATCH {{server}}/boards/2/status
Content-Type: application/json

{
    "status": "a"
}


### POST
POST {{server}}/auth/signup
Content-Type: application/json

{    
    "username": "iks55",
    "password": "Sniper123$asdf" 
}

### POST
POST {{server}}/auth/signup
Content-Type: application/json

{    
    "username": "iks5",
    "password": "Sniper123$" 
}


### POST
POST {{server}}/auth/signin
Content-Type: application/json

{    
    "username": "iks55",
    "password": "Sniper123$" 
}

### POST
POST {{server}}/auth/authTest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
Content-Type: application/json
