##########################################
### VSCode Extension - REST Client 필요 ###
##########################################
### 통신 테스트 할 서버
@server = http://localhost:3000

### GET 요청 보내기
GET {{server}}/boards

### POST
POST {{server}}/boards
Content-Type: application/json

{    
    "title": "first IK",
    "description": "최초의 익" 
}